//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsipovKirill320_KittenDogApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int IDPhoto { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] PhotoSource { get; set; }
    }
}
